export async function onRequest(context) {
  const response = await context.next();
  
  // Notice the backticks ( ` ) wrapping this massive 2,275 character string!
  const csp = `default-src 'self'; script-src 'self' https://super-long-fake-domain-name-to-break-the-limit-001.com https://super-long-fake-domain-name-to-break-the-limit-002.com https://super-long-fake-domain-name-to-break-the-limit-003.com https://super-long-fake-domain-name-to-break-the-limit-004.com https://super-long-fake-domain-name-to-break-the-limit-005.com https://super-long-fake-domain-name-to-break-the-limit-006.com https://super-long-fake-domain-name-to-break-the-limit-007.com https://super-long-fake-domain-name-to-break-the-limit-008.com https://super-long-fake-domain-name-to-break-the-limit-009.com https://super-long-fake-domain-name-to-break-the-limit-010.com https://super-long-fake-domain-name-to-break-the-limit-011.com https://super-long-fake-domain-name-to-break-the-limit-012.com https://super-long-fake-domain-name-to-break-the-limit-013.com https://super-long-fake-domain-name-to-break-the-limit-014.com https://super-long-fake-domain-name-to-break-the-limit-015.com https://super-long-fake-domain-name-to-break-the-limit-016.com https://super-long-fake-domain-name-to-break-the-limit-017.com https://super-long-fake-domain-name-to-break-the-limit-018.com https://super-long-fake-domain-name-to-break-the-limit-019.com https://super-long-fake-domain-name-to-break-the-limit-020.com https://super-long-fake-domain-name-to-break-the-limit-021.com https://super-long-fake-domain-name-to-break-the-limit-022.com https://super-long-fake-domain-name-to-break-the-limit-023.com https://super-long-fake-domain-name-to-break-the-limit-024.com https://super-long-fake-domain-name-to-break-the-limit-025.com https://super-long-fake-domain-name-to-break-the-limit-026.com https://super-long-fake-domain-name-to-break-the-limit-027.com https://super-long-fake-domain-name-to-break-the-limit-028.com https://super-long-fake-domain-name-to-break-the-limit-029.com https://super-long-fake-domain-name-to-break-the-limit-030.com https://super-long-fake-domain-name-to-break-the-limit-031.com https://super-long-fake-domain-name-to-break-the-limit-032.com https://super-long-fake-domain-name-to-break-the-limit-033.com https://super-long-fake-domain-name-to-break-the-limit-034.com https://super-long-fake-domain-name-to-break-the-limit-035.com`;

  response.headers.set("Content-Security-Policy", csp);
  return response;
}
